[package]
name = "subtitles-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
similar = "2.2.1"
soloud = "1.0.3"
crt-term-gl = { path = "crt-term-gl" }
glfw = "0.52.0"
glow = "0.12.3"
